### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AchrafBenmasaoud** [ddulshan/IOC-Verifier#1]
Hey @ddulshan 

I love your script, and it works well! I have a question, though, if you don't mind. 

Is it also possible that the script automatically checks the IP/hashes on which system you're logged in instead of giving the IP manually?

**Comment by ddulshan** [comment]
Hi @AchrafBenmasaoud 

Do you mean to check all the hashes of the files in the system the script is running on? If so, this is not a option that is currently supported. You can workaround this by separately generating a file with all hashes of the system with "Get-FileHash" powershell cmdlet with recursive option from the root directory. As I've not personally tried this it could cause unexpected results, use with cautious.

**Comment by AchrafBenmasaoud** [comment]
Thank you @ddulshan 

That would be an option. But even if it works,  virustotal, Kaspersky etc have a limit. So you can't check thousands of hashes in a fast manner. 

Maybe generate only on specific directories the hashes which you can copy and paste into the ioc.txt file?

**Comment by ddulshan** [comment]
Yes the number of hashes would certainly be an issue, I hoped you had it covered with a premium VT account or such. 

> Maybe generate only on specific directories the hashes which you can copy and paste into the ioc.txt file?

Even with the hashes divided by specific directories you'd still end up with the same number of Hashes. If you mean to get the hashes of files from a specific one directory you'd have to do this manually with the powershell cmdlet I mentioned before or implement your own fork/pull.

A quick workaround would be to replace following one line 684 as of `v1.2`:

> Get-Content $ioc_file | ForEach-Object {

with:

> (Get-FileHash .\Reports\\*).Hash | ForEach-Object {

replacing `.\Reports\` with the directory you want to retrieve all hashes for.

**Comment by AchrafBenmasaoud** [comment]
I am sorry for the late reply. Next week I will look into it. Thanks in advance!
